name: 'StackQL Assert'

on:
  push:
    branches:
    - main
  pull_request:
jobs:
  stackql-exec-google-example:
    runs-on: ubuntu-latest
    name: 'Assert test '

    steps: 
    - name: Checkout
      uses: actions/checkout@v3

  
    - name: Prep Google Creds (bash)
      shell: bash
      run: | ## use the base64 encoded secret to create json file
        sudo echo ${{ secrets.GOOGLE_CREDS }} | base64 -d > sa-key.json

    - name: query test statement example with auth_obj_path
      uses: ./
      with:
        auth_obj_path: './stackql_scripts/auth.json'
        test_query: |
            REGISTRY PULL google v23.01.00116;
            SELECT name, status
            FROM google.compute.instances 
            WHERE project = 'stackql-demo' AND zone = 'australia-southeast1-a' AND name = 'stackql-demo-001';
        expected_results_str: ' [{"name":"stackql-demo-001","status":"TERMINATED"}]'

    - name: query test file example with auth_obj_path
      uses: ./
      with:
        auth_obj_path: './stackql_scripts/auth.json'
        test_query_file_path: './stackql_scripts/google-example.iql'
        expected_results_str: ' [{"name":"stackql-demo-001","status":"TERMINATED"}]'

    - name: query test statement example with auth string
      uses: ./
      with:
        auth_str: '{ "google": { "type": "service_account",  "credentialsfilepath": "sa-key.json" }}'
        test_query: |
            REGISTRY PULL google v23.01.00116;
            SELECT name, status
            FROM google.compute.instances 
            WHERE project = 'stackql-demo' AND zone = 'australia-southeast1-a' AND name = 'stackql-demo-001';
        expected_results_str: '[{"name":"stackql-demo-001","status":"TERMINATED"}]'

    - name: query test file example with auth string
      uses: ./
      with:
        auth_str: '{ "google": { "type": "service_account",  "credentialsfilepath": "sa-key.json" }}'
        test_query_file_path: './stackql_scripts/google-example.iql'
        expected_results_str: '[{"name":"stackql-demo-001","status":"TERMINATED"}]'

    - name: query test file while expected result is a file
      uses: ./
      with:
        auth_str: '{ "google": { "type": "service_account",  "credentialsfilepath": "sa-key.json" }}'
        test_query_file_path: './stackql_scripts/google-example.iql'
        expected_results_file_path: './github/workflows/expected_results.json'
          


